/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDescription {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface NewLocation {
    }
}
declare global {
    interface HTMLAppDescriptionElement extends Components.AppDescription, HTMLStencilElement {
    }
    var HTMLAppDescriptionElement: {
        prototype: HTMLAppDescriptionElement;
        new (): HTMLAppDescriptionElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLNewLocationElement extends Components.NewLocation, HTMLStencilElement {
    }
    var HTMLNewLocationElement: {
        prototype: HTMLNewLocationElement;
        new (): HTMLNewLocationElement;
    };
    interface HTMLElementTagNameMap {
        "app-description": HTMLAppDescriptionElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "new-location": HTMLNewLocationElement;
    }
}
declare namespace LocalJSX {
    interface AppDescription {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface NewLocation {
    }
    interface IntrinsicElements {
        "app-description": AppDescription;
        "app-home": AppHome;
        "app-root": AppRoot;
        "new-location": NewLocation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-description": LocalJSX.AppDescription & JSXBase.HTMLAttributes<HTMLAppDescriptionElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "new-location": LocalJSX.NewLocation & JSXBase.HTMLAttributes<HTMLNewLocationElement>;
        }
    }
}
